Extand api to create netinterface and select preferred
xcp-ng/sm pull request #47
Opened 2023-11-14 12:07 UTC by benjamreis

2023-11-15 17:28 UTC, stormi commented
It would be good if the commit message would make it clear that this is about the linstor driver, and also explain in the commit message why this change is needed, what API it adds, and for what.

Also: `s/extand/extend/`

2023-11-27 15:19 UTC, Wescoeur commented on drivers/linstorvolumemanager.py
> +    def create_netinterface(self, hostname, iface_name, ip_addr):
`create_node_interface` instead? It seems more uniform with the second method.

2023-11-27 15:25 UTC, Wescoeur requested changes

2023-11-27 15:25 UTC, Wescoeur commented on drivers/linstorvolumemanager.py
> +                'Unable to create interface on`{}`: {}'.format(hostname, ', '.join(
Missing space: "interface on `{}`"

2023-11-27 15:25 UTC, Wescoeur commented on drivers/linstorvolumemanager.py
> +    def create_netinterface(self, hostname, iface_name, ip_addr):
`name` instead of `iface_name`?

2023-11-27 15:25 UTC, Wescoeur commented on drivers/linstorvolumemanager.py
> +                'Unable to set prefered interface on`{}`: {}'.format(hostname, ', '.join(
`preferred`

2023-11-27 15:25 UTC, Wescoeur commented on drivers/linstor-manager
> +        'interfaceCreate': interface_create,
`createNodeInterface`

2023-11-27 15:25 UTC, Wescoeur commented on drivers/linstor-manager
> +        'nodeSetPreferredInterface': set_node_preferred_interface
`setNodePreferredInterface`

2023-11-29 15:54 UTC, merged