Add new debug log in linstorhostcall
xcp-ng/sm pull request #67
Opened 2024-08-05 08:47 UTC by Nambrok

Add new debug logs in linstorhostcall and correct one that was incorrect.

2024-08-05 12:11 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                    util.SMlog("Success accessing on attached node for device {}: {}: {}".format(remote_args["devicePath"], remote_method, str(response)), priority=util.LOG_DEBUG)
remote_args["devicePath"] => device_path

2024-08-05 12:11 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                    util.SMlog("Success accessing on attached node for device {}: {}: {}".format(remote_args["devicePath"], remote_method, str(response)), priority=util.LOG_DEBUG)
Could be a good idea to log vdi_uuid too.

2024-08-05 12:11 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                    'Failed to call method on attached host. Trying accessing on master... (cause: {})'.format(e),
Symmetric: log VDI path / UUID

2024-08-05 12:11 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                util.SMlog("Success accessing on master for device {}: {}: {}".format(remote_args["devicePath"], remote_method, str(response)), priority=util.LOG_DEBUG)
Same comments here :)

2024-08-05 12:41 UTC, Nambrok commented
```
Aug  5 14:40:47 r620-s1 SM: [32009] Failed to call method on attached node for device /dev/drbd/by-res/xcp-volume-bc98c086-a20d-40d8-bf53-c2ca7623071a/0 (3c7212b2-1739-41f9-9f47-83ae63962356): getVHDInfo. Trying accessing on master... (cause: list index out of range)
Aug  5 14:40:48 r620-s1 SM: [32009] Success accessing on master for device /dev/drbd/by-res/xcp-volume-bc98c086-a20d-40d8-bf53-c2ca7623071a/0 (3c7212b2-1739-41f9-9f47-83ae63962356): getVHDInfo: {"path": "/dev/drbd/by-res/xcp-volume-bc98c086-a20d-40d8-bf53-c2ca7623071a/0", "hidden": 1, "sizePhys": 203944448, "uuid": "3c7212b2-1739-41f9-9f47-83ae63962356", "sizeVirt": 2147483648}
Aug  5 14:40:48 r620-s1 SM: [32009] Failed to call method on attached node for device /dev/drbd/by-res/xcp-volume-fc3efedf-4a65-4ecd-8398-fc5507d80249/0 (31644084-1b89-4cfd-b4b5-c57b653cb8d4): getVHDInfo. Trying accessing on master... (cause: list index out of range)
Aug  5 14:40:48 r620-s1 SM: [32009] Success accessing on master for device /dev/drbd/by-res/xcp-volume-fc3efedf-4a65-4ecd-8398-fc5507d80249/0 (31644084-1b89-4cfd-b4b5-c57b653cb8d4): getVHDInfo: {"uuid": "31644084-1b89-4cfd-b4b5-c57b653cb8d4", "parentUuid": "3c7212b2-1739-41f9-9f47-83ae63962356", "sizeVirt": 2147483648, "sizePhys": 4329472, "parentPath": "../xcp-volume-bc98c086-a20d-40d8-bf53-c2ca7623071a/0", "path": "/dev/drbd/by-res/xcp-volume-fc3efedf-4a65-4ecd-8398-fc5507d80249/0", "hidden": 0}
```
It looks like that.

2024-08-08 08:27 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                        "Success accessing on attached node for device {} ({}): {}: {}".format(device_path, vdi_uuid, remote_method, str(response)),
Maybe `Successful access`?
```suggestion
                        "Successful access on attached node for device {} ({}): `{}` = {}".format(device_path, vdi_uuid, remote_method, str(response)),
```

2024-08-08 08:27 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                        "Success accessing on another node for device {} ({}): {}: {}".format(device_path, vdi_uuid, remote_method, str(response)),
```suggestion
                        "Successful access on attached node for device {} ({}): `{}` = {}".format(device_path, vdi_uuid, remote_method, str(response)),
```

2024-08-08 08:29 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                util.SMlog("Success accessing on master for device {} ({}): {}: {}".format(device_path, vdi_uuid, remote_method, str(response)), priority=util.LOG_DEBUG)
```suggestion
                util.SMlog('Successful access on attached node for device {} ({}): `{}` = {}'.format(device_path, vdi_uuid, remote_method, str(response)), priority=util.LOG_DEBUG)
```

2024-08-08 08:30 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                    'Failed to obtain primary node for device {} ({}): {}. Trying with another node...'.format(device_path, vdi_uuid, remote_method),
We don't search a primary node here, but a primary volume or lock.

2024-08-08 08:31 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                    'Failed to call method on master for device {} ({}): {}. Finding primary node... (cause: {})'.format(device_path, vdi_uuid, remote_method, e),
I know that was my message, but it's probably a good idea to change the "primary node" text.

2024-08-08 08:32 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                        "Success accessing on attached node for device {} ({}): {}: {}".format(device_path, vdi_uuid, remote_method, str(response)),
We can use a function to log this message because it's duplicated in many parts.

2024-08-08 08:33 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +                        "Success accessing on primary node for device {} ({}): {}: {}".format(device_path, vdi_uuid, remote_method, str(response)),
```suggestion
                        "'Successful access on attached node for device {} ({}): `{}` = {}'.format(device_path, vdi_uuid, remote_method, str(response)),
```

2024-08-08 09:22 UTC, Wescoeur requested changes

2024-08-08 09:22 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +    )
```suggestion
def log_successful_call(target_host, device_path, vdi_uuid, remote_method, response):
    util.SMlog(
        'Successful access on {} for device {} ({}): `{}` => {}'.format(target_host, device_path, vdi_uuid, remote_method, str(response)),
        priority=util.LOG_DEBUG
    )
```

2024-08-08 09:22 UTC, Wescoeur commented on drivers/linstorvhdutil.py
> +    )
```suggestion
def log_failed_call(target_host, next_target, device_path, vdi_uuid, remote_method, e):
    util.SMlog(
        'Failed to call method on {} for device {} ({}): {}. Trying accessing on {}... (cause: {})'.format(target_host, device_path, vdi_uuid, remote_method, next_target, e),
        priority=util.LOG_DEBUG
    )
```

2024-08-08 09:30 UTC, Wescoeur approved these changes

2024-08-08 11:43 UTC, benjamreis approved these changes

2024-08-09 07:31 UTC, merged